module.exports ={
    "getAlAvailableBills":"/api/v1/biils/get-all-availabe",
    "getAllRecurringSubscribers":"/api/v1/bills/get-all-subscribers",
    "ngAirtimeRecharge": "/api/v1/airtime/recharge",
    "ngBulkRecharge" : "/api/v1/airtime/bulk-recharge",
    "ngGetAllTransactions":"/api/v1/airtime/get-alltransactions",
    "ngGetSingleTransaction":"/api/v1/airtime/get-singl-transaction",
    "ngStatusOfBill":"/api/v1/airtime/status",
    "ngCancelrecurring":"/api/v1/airtime/cancel-recuring",
    "hourlyRecurring":"/api/v1/airtime/hourly-recuring",
    "daillyRecurring":"/api/v1/airtime/daily-recuring",
    "weeklyRecurring":"/api/v1/airtime/weekly-recuring",
    "monthlylyRecurring":"/api/v1/airtime/monthly-recuring",
    "ngGetAmountForAProduct": "/api/v1/airtime/get-amount-to-pay",
}